// Popular stock symbols including Korean stocks
export const popularStockSymbols = [
  // Korean stocks (KOSPI)
  "005930.KS", // Samsung Electronics
  "000660.KS", // SK Hynix
  "051910.KS", // LG Chem
  "035420.KS", // NAVER
  "005380.KS", // Hyundai Motor
  "000270.KS", // Kia Motors
  "068270.KS", // Celltrion
  "035720.KS", // Kakao
  "207940.KS", // Samsung Biologics
  "006400.KS", // Samsung SDI
  "055550.KS", // Shinhan Financial Group
  "105560.KS", // KB Financial Group
  "036570.KS", // NCsoft
  "017670.KS", // SK Telecom
  "015760.KS", // Korea Electric Power
  "032830.KS", // Samsung Life Insurance
  "012330.KS", // Hyundai Mobis
  "028260.KS", // Samsung C&T
  "066570.KS", // LG Electronics
  "096770.KS", // SK Innovation

  // US stocks
  "AAPL",
  "MSFT",
  "GOOGL",
  "AMZN",
  "META",
  "TSLA",
  "NVDA",
  "JPM",
  "V",
  "JNJ",
  "WMT",
  "PG",
  "MA",
  "UNH",
  "HD",
  "BAC",
  "XOM",
  "PFE",
  "CSCO",
  "VZ",
  "NFLX",
  "ADBE",
  "CRM",
  "INTC",
  "CMCSA",
  "PEP",
  "KO",
  "ABT",
  "MRK",
  "DIS",
  "PYPL",
  "TMO",
  "COST",
  "ACN",
  "NKE",
  "AVGO",
  "TXN",
  "NEE",
  "LLY",
  "MDT",
  "DHR",
  "UNP",
  "BMY",
  "PM",
  "T",
  "QCOM",
  "SBUX",
  "LIN",
  "AMD",
  "IBM",
  "AMGN",
  "HON",
  "CVX",
  "LOW",
  "ORCL",
  "GS",
  "MMM",
  "INTU",
  "BA",
  "CAT",
  "GE",
  "AXP",
  "BLK",
  "GILD",
  "MDLZ",
  "TGT",
  "ISRG",
  "BKNG",
  "SPGI",
  "MO",
  "CHTR",
  "TJX",
  "TMUS",
  "CB",
  "MS",
  "RTX",
  "C",
  "ANTM",
  "CCI",
  "VRTX",
  "ZTS",
  "PLD",
  "USB",
  "AMAT",
  "ADP",
  "CME",
  "CL",
  "DUK",
  "SO",
  "ATVI",
  "SYK",
  "D",
  "CSX",
  "ICE",
  "REGN",
  "APD",
  "NSC",
  "EL",
  "ITW",
  "FIS",
]

// Korean company names mapping
export const koreanCompanyNames: Record<string, string> = {
  "005930.KS": "삼성전자",
  "000660.KS": "SK하이닉스",
  "051910.KS": "LG화학",
  "035420.KS": "네이버",
  "005380.KS": "현대자동차",
  "000270.KS": "기아",
  "068270.KS": "셀트리온",
  "035720.KS": "카카오",
  "207940.KS": "삼성바이오로직스",
  "006400.KS": "삼성SDI",
  "055550.KS": "신한지주",
  "105560.KS": "KB금융",
  "036570.KS": "엔씨소프트",
  "017670.KS": "SK텔레콤",
  "015760.KS": "한국전력",
  "032830.KS": "삼성생명",
  "012330.KS": "현대모비스",
  "028260.KS": "삼성물산",
  "066570.KS": "LG전자",
  "096770.KS": "SK이노베이션",

  // US companies with Korean translations
  AAPL: "애플",
  MSFT: "마이크로소프트",
  GOOGL: "알파벳",
  AMZN: "아마존",
  META: "메타",
  TSLA: "테슬라",
  NVDA: "엔비디아",
  JPM: "JP모건",
  V: "비자",
  JNJ: "존슨앤존슨",
}

// Korean sector names
export const koreanSectors: Record<string, string> = {
  Technology: "기술",
  Healthcare: "헬스케어",
  "Financial Services": "금융 서비스",
  "Consumer Cyclical": "소비재",
  "Communication Services": "통신 서비스",
  Industrials: "산업재",
  "Consumer Defensive": "필수소비재",
  Energy: "에너지",
  "Basic Materials": "원자재",
  "Real Estate": "부동산",
  Utilities: "유틸리티",
}

// Korean industry names
export const koreanIndustries: Record<string, string> = {
  Software: "소프트웨어",
  Semiconductors: "반도체",
  Hardware: "하드웨어",
  "IT Services": "IT 서비스",
  Pharmaceuticals: "제약",
  "Medical Devices": "의료기기",
  Biotechnology: "생명공학",
  "Healthcare Services": "의료 서비스",
  Banks: "은행",
  Insurance: "보험",
  "Asset Management": "자산관리",
  "Financial Technology": "핀테크",
  Retail: "소매",
  Automotive: "자동차",
  Entertainment: "엔터테인먼트",
  Hospitality: "호텔 및 레저",
  Telecom: "통신",
  Media: "미디어",
  "Social Media": "소셜미디어",
  Aerospace: "항공우주",
  Defense: "방위산업",
  Machinery: "기계",
  Transportation: "운송",
  Food: "식품",
  Beverages: "음료",
  "Household Products": "가정용품",
  "Personal Products": "개인용품",
  "Oil & Gas": "석유 및 가스",
  "Renewable Energy": "재생에너지",
  "Energy Equipment": "에너지 장비",
  "Energy Services": "에너지 서비스",
  Chemicals: "화학",
  "Metals & Mining": "금속 및 광업",
  "Paper & Forest Products": "종이 및 임산물",
  "Construction Materials": "건축자재",
  REITs: "부동산투자신탁",
  "Real Estate Services": "부동산 서비스",
  Development: "개발",
  "Property Management": "자산관리",
  "Electric Utilities": "전력 유틸리티",
  "Gas Utilities": "가스 유틸리티",
  "Water Utilities": "수도 유틸리티",
  "Renewable Utilities": "재생 유틸리티",
}
