# .github/workflows/main_stock-tracker-webapp.yml

name: Build and deploy Node.js app to Azure Web App - stock-tracker-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          # package.json에 명시된 Node.js 버전을 사용하는 것이 좋습니다.
          node-version: '20' 
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          # GitHub Actions Secrets에 저장된 환경 변수 사용
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL: https://<YOUR_APP_NAME>.azurewebsites.net # 본인 앱 이름으로 변경

      # Standalone 폴더로 배포에 필요한 파일들 복사
      - name: Copy files for deployment
        run: |
          cp -r .next/standalone .
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static
          cp server.js .next/standalone/server.js
          cp web.config .next/standalone/web.config

      # 배포 패키지 압축
      - name: Create deployment package
        run: zip -r deployment.zip .next/standalone

      # 배포 아티팩트 업로드
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # 빌드 아티팩트 다운로드
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip deployment.zip -d ./release

      # Azure Web App에 배포
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stock-tracker-webapp' # Azure Web App 이름
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # GitHub Secret에 저장된 배포 프로필
          package: './release'
