name: Build and deploy Node.js app to Azure Web App - stock-tracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present
        env:
          CI: true
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Copy additional files (for standalone deployment)
        run: |
          mkdir -p .next/standalone
          cp package.json .next/standalone/
          cp -r public .next/standalone/
          cp -r .next/static .next/standalone/.next/
          cp server.js .next/standalone/ || true
          cp web.config .next/standalone/ || true

      - name: Zip artifact for deployment
        run: |
          cd .next/standalone
          zip -r ../../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C92AA86D556B4642940F5E13D341A48B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7636FFF16793426D8F0F5FC48F596CE3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DB0414C672C3454B91540BB8EA68E35F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stock-tracker-webapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_XXXXX }}
          package: .